mkdir -p results/false-michel_current-01 && \python train_eval.py  \
   -d cifar100    \
    --data_root data/cifar100    \
    --optimizer adam   \
      --head_freeze   \
      --freeze_ratio 0.1   \
        --freeze_subset 0.2   \
        --shuffle_classes false \
        --scoring_method voita   \
        --head_selection michel_current    \
         --log_dir ./results/false-michel_current-01    2>&1 | tee results/false-michel_current-01/false-michel_current-01.txt
